# Generated by Django 3.1.5 on 2021-04-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='pages',
        ),
        migrations.AddField(
            model_name='size',
            name='type',
            field=models.CharField(choices=[('horizontal', 'Горизонтальный'), ('vertical', 'Вертикальный'), ('square', 'Квадрат')], default='vertical', max_length=20),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=15),
        ),
    ]
