# Generated by Django 3.1.5 on 2021-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
