# Generated by Django 3.1.5 on 2021-04-15 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20210415_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='album.cover'),
        ),
        migrations.AlterField(
            model_name='album',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='album.paper'),
        ),
        migrations.AlterField(
            model_name='album',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='album.size'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный'), ('blue', 'Синий'), ('red', 'Красный'), ('green', 'Зеленый'), ('pink', 'Розовый'), ('yellow', 'Желтый')], default='white', max_length=20),
        ),
    ]
