# Generated by Django 3.1.5 on 2021-04-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20210415_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='color',
        ),
    ]
