# Generated by Django 3.1.5 on 2021-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_auto_20210415_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='in_progress', max_length=20),
        ),
    ]
